name: Verify

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!release'

jobs:
  test:

    runs-on: ubuntu-latest
    env:
      LANG: "ja_JP.UTF-8"
    steps:
    - name: ja_JP.UTF-8
      run: |
          sudo locale-gen ja_JP.UTF-8
          sudo update-locale LANG=ja_JP.UTF-8
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Verify with Maven
      env:
        TZ: 'Asia/Tokyo'
      run: mvn verify --file pom.xml
